spring.application.name=Tienda_Pablo
# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Paulus_Pablo
spring.datasource.username=Pablo09
spring.datasource.password=sanpeter04

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true